typography_spectrum: 0.5934479
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#f8bb2d'
    - '#333333'
    - '#979097'
  brandStrength: 0
  lightness: 0.124855
  saturation: 0.0625
  rhythmicContrast: 0.75
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 1
analytics:
  google: null
  facebook: null
  twitter: null
name: Sabbath Brewing Co.
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Raspberry Wheat Ale
purpose: []
